title: "maxulysse.github.io"
description: "Interested in Bioinformatics, Reproducible Research, Automation, Data Integration and Visualization..."
baseurl: ""
url: "https://maxulysse.github.io"
author:
  name: Maxime Garcia
  twitter: gau
  github: maxulysse

logo:
  path: "/assets/img/favicons/android-chrome-192x192.png"
  width: 192
  height: 192

highlighter: rouge
markdown: kramdown
paginate: 12
permalink: pretty
theme: jekyll-theme-minimal

sass:
  sass_dir: _sass
  style: compact

gems:
  - jekyll-feed
  - jekyll-minifier
  - jekyll-paginate
  - jekyll-sitemap

include:
  - "_pages"

exclude:
  - [vendor]
  - "LICENSE"
  - "README.md"
  - "assets/scripts/test.sh"
