# Site settings
title: "maxulysse.github.io"
description: "Interested in Bioinformatics, Reproducible Research, Automation, Data Integration and Visualization..."
baseurl: ""
url: "https://maxulysse.github.io"
author:
  name: Maxime Garcia
  twitter: gau
  github: maxulysse

logo:
  path: "/img/favicons/android-chrome-192x192.png"
  width: 192
  height: 192

# Build settings
paginate: 10 # the number of post per page
highlighter: rouge
markdown: kramdown
permalink: pretty

sass:
  sass_dir: _sass
  style: compressed # Possible values -> nested / expanded / compact / compressed

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Handling Reading
exclude:
  - "LICENSE"
